model:
  arch: proteinchat
  model_type: pretrain_vicuna

  # Stage 1
  # freeze_protein_encoder: True
  # freeze_lp: False
  # freeze_llama: True

  # Stage 2
  freeze_protein_encoder: True
  freeze_lp: True
  freeze_llama: False

  llama_model: "/data3/ruiyi/vicuna-13b-v1.5"
  prompt: ""

  max_txt_len: 405
  end_sym: "###"
  low_resource: True
  embedding_agg: 1
  peft_ckpt: ''
  glm_load_path: /data3/ruiyi/proteinglm-1b-mlm
  stage1_ckpt_hug: /data3/ruiyi/proteinchat/proteinchat_glm_1.pth
  stage1_ckpt_code: /data2/mingjia/protein/xtrimopglm/checkpoint_3_code.pth
  
datasets:
  seq:
    data_type: protein
    build_info:
      train:
        storage: /data3/ruiyi/proteinchat/CLEAN_all_train_valid_splits/split10/split10_train_split_1_converted

run:
  task: protein_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  # init_lr: 5e-6
  # min_lr: 5e-6
  # warmup_lr: 5e-6
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  accum_grad_iters: 8

  weight_decay: 0.01
  max_epoch: 10
  iters_per_epoch: 6543 #34390 # 68782 # 
  batch_size_train: 2
  batch_size_eval: 1
  num_workers: 4
  warmup_steps: 200

  seed: 42
  output_dir: "/data3/ruiyi/proteinchat/ckpt/clean"

  amp: True
  resume_ckpt_path: null

  printable: False # whether all ranks can print (True) or only rank 0 can print (False)

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
